site_name: Kubernetes Quick Dive
pages:
  - Home: "index.md"
  - Using minikube to setup single node environment: "minikube.md" 
  - Visualising Kuberentes Cluster: "kube_visualizer.md"
  - Creating Deployments: "6_kubernetes_deployment.md"
  - Service Endpoints: "7_exposing_app_with_service.md"
  - Rollouts and Rollbacks: "8_rollouts_and_rollbacks.md"
docs_dir: chapters
theme: readthedocs
plugins:
    - search
